FROM ubuntu:jammy

# Docker install
RUN apt-get update && apt-get install --no-install-recommends -y \
	apt-transport-https \
	ca-certificates \
	curl \
	gnupg-agent \
	software-properties-common \
	git \
	jq \
	libicu70 \
	ca-certificates \
	wget
	
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN apt-key fingerprint 0EBFCD88

RUN add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"
RUN apt-get update && apt-get install --no-install-recommends -y docker-ce docker-ce-cli containerd.io

RUN mkdir /home/agent

# create new user 
RUN useradd agent
RUN chown -R agent /home/agent
RUN chmod u+rw /home/agent

WORKDIR /home/agent/

# add agent user to docker group
RUN groupadd docker
RUN usermod -aG docker agent
RUN newgrp docker

# install pwsh 
RUN 
